import { describe, expect, it } from 'vitest'
import * as api from '$lib/index.js'

const PUBLIC_API = [
    'DataGrid',
    'Grid',
    'createDataGrid',
    'getCellValue',
    'SELECTION_COLUMN_ID',
    'SNAPSHOT_VERSION',
    'defineDataGridConfig',
    'resetDataGridConfig',
    'registerDataGridIcons',
    'datagridIcons',
    'defaultLabels',
    'mergeLabels',
    'PIPELINE_ORDER',
    'columnOps',
    'editing',
    'filtering',
    'pagination',
    'rowPinning',
    'rowReorder',
    'selection',
    'sorting',
    'virtualization',
    'getColumnOps',
    'getEditing',
    'getFiltering',
    'getPagination',
    'getRowPinning',
    'getRowReorder',
    'getSelection',
    'getSorting',
    'getVirtualization',
    'toFilterRequest',
    'toSortRequest',
    'pickColumns',
    'rowsToMatrix',
    'toCsv',
    'toTsv',
    'withHeaderRow',

    'autoColumns',
    'isDataRow',
    'isLoadingRow',
    'isDetailNode',
    'ShareTooLongError',
    'advancedFilter',
    'commandPalette',
    'conditionalFormatting',
    'dataImport',
    'findReplace',
    'formula',
    'grouping',
    'masterDetail',
    'policy',
    'rangeSelection',
    'savedViews',
    'serverRowModel',
    'showValuesAs',
    'tree',
    'workerDataSource',
    'getAdvancedFilter',
    'getCommandPalette',
    'getConditionalFormatting',
    'getDataImport',
    'getFindReplace',
    'getFormula',
    'getGridContext',
    'getGridElement',
    'getGrouping',
    'getMasterDetail',
    'getPolicy',
    'getRangeSelection',
    'getSavedViews',
    'getServerRowModel',
    'getShowValuesAs',
    'getTree',
    'aggregate',
    'totalsKindOf',
    'FormulaError',
    'isFormulaError',
    'FUNCTION_NAMES',
    'localStorageViews'
].sort()

describe('public API', () => {
    it('exports exactly what it means to export', () => {
        expect(Object.keys(api).sort()).toEqual(PUBLIC_API)
    })

    it('exports no symbol that is only wiring', () => {
        for (const name of [
            'formatCurrency',
            'formatDate',
            'formatNumber',
            'formatPercent',
            'isBlank',
            'toDate',
            'toNumber',
            'formatCellText',
            'datagridVariants',
            'setGridContext',
            'GridCellValue',
            'DEFAULT_EMPTY_TEXT',
            'DEFAULT_CSV_DELIMITER',
            'HEADER_ROW',
            'ROW_HANDLE_COLUMN_ID',
            'isSyntheticColumn',
            'dataColumns',
            'downloadCsv',
            'neutralizeFormula',
            'documentLocale',
            'resolveLocale',
            'defaultAnnouncerStrings',
            'filterConditions',
            'isFilterGroup',
            'normalizeFilterEntry',
            'DATE_OPS',
            'NUMBER_OPS',
            'TEXT_OPS'
        ]) {
            expect(api).not.toHaveProperty(name)
        }
    })
})
