import type {
    DataGridLabels,
    DataGridLabelsInput,
    DateFilterOp,
    NumberFilterOp,
    TextFilterOp
} from '../types/index.js'

export const TEXT_OPS: TextFilterOp[] = [
    'contains',
    'notContains',
    'equals',
    'notEqual',
    'startsWith',
    'endsWith',
    'blank',
    'notBlank'
]
export const NUMBER_OPS: NumberFilterOp[] = [
    'eq',
    'neq',
    'gt',
    'gte',
    'lt',
    'lte',
    'between',
    'blank',
    'notBlank'
]
export const DATE_OPS: DateFilterOp[] = [
    'equals',
    'notEqual',
    'before',
    'after',
    'between',
    'blank',
    'notBlank'
]

export const defaultLabels: DataGridLabels = {
    search: 'Search...',
    activeFilters: 'Active filters',
    removeFilter: (column) => `Remove filter ${column}`,
    clearAllFilters: 'Clear all',
    chooseColumns: 'Choose columns',
    rowDensity: 'Row density',
    densityCompact: 'Compact density',
    densityStandard: 'Standard density',
    densityComfortable: 'Comfortable density',

    columnMenu: (column) => `${column} column menu`,
    resizeColumn: (column) => `Resize ${column} column`,
    resizeGroup: (group) => `Resize ${group} group`,
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    clearSort: 'Clear sort',
    pinLeft: 'Pin left',
    pinRight: 'Pin right',
    unpin: 'Unpin',
    openFilter: 'Filter...',
    autosize: 'Autosize',
    hideColumn: 'Hide column',
    collapseGroup: (group) => `Collapse ${group}`,
    expandGroup: (group) => `Expand ${group}`,

    filterColumn: (column) => `Filter ${column}`,
    filterOperator: (ordinal) => (ordinal > 1 ? `Filter operator ${ordinal}` : 'Filter operator'),
    filterValue: (ordinal) => (ordinal > 1 ? `Filter value ${ordinal}` : 'Filter value'),
    filterRowValue: (column) => `${column} filter value`,
    filterUpperBound: (ordinal) =>
        ordinal > 1 ? `Filter upper bound ${ordinal}` : 'Filter upper bound',
    valuePlaceholder: 'Value...',
    upperBoundPlaceholder: 'To...',
    searchValues: 'Search values...',
    blankValue: '(blank)',
    anyValue: '(any)',
    combineConditions: 'Combine conditions',
    addCondition: 'Add condition',
    removeCondition: 'Remove condition',
    matchCase: 'Match case',
    apply: 'Apply',
    clear: 'Clear',
    and: 'And',
    or: 'Or',
    yes: 'True',
    no: 'False',
    textOps: {
        contains: 'Contains',
        notContains: 'Does not contain',
        equals: 'Equals',
        notEqual: 'Not equal',
        startsWith: 'Starts with',
        endsWith: 'Ends with',
        blank: 'Is blank',
        notBlank: 'Is not blank'
    },
    numberOps: {
        eq: '=',
        neq: '≠',
        gt: '>',
        gte: '≥',
        lt: '<',
        lte: '≤',
        between: 'Between',
        blank: 'Is blank',
        notBlank: 'Is not blank'
    },
    dateOps: {
        equals: 'Equals',
        notEqual: 'Does not equal',
        before: 'Before',
        after: 'After',
        between: 'Between',
        blank: 'Is blank',
        notBlank: 'Is not blank'
    },

    selectRow: (position) => `Select row ${position}`,
    selectAllRows: 'Select all rows',
    rowActions: 'Row actions',
    dragRow: (position) => `Move row ${position}`,
    expandRow: 'Expand row',
    collapseRow: 'Collapse row',

    rowsPerPage: 'Rows per page',
    pageSizeOption: (size) => `${size} / page`,
    pageRange: (from, to, total) =>
        `${from.toLocaleString()}-${to.toLocaleString()} of ${total.toLocaleString()}`,
    totalRows: (total) => `${total.toLocaleString()} rows`,
    filteredRows: (filtered, total) =>
        `${filtered.toLocaleString()} of ${total.toLocaleString()} rows`,
    selectedRows: (count) => `${count.toLocaleString()} selected`,
    noData: 'No data',
    retry: 'Retry',

    copy: 'Copy',
    copyWithHeaders: 'Copy with headers',
    exportCsv: 'Export CSV',
    exportAllRows: 'All rows',
    exportLoadedRows: 'Loaded rows',
    exportSelectedRows: 'Selected rows',
    clearSelection: 'Clear selection',

    groupBy: 'Group by',
    groupPanelEmpty: 'No grouping: add a column to group by',
    addGroup: 'Add group',
    clearGroups: 'Clear',
    moveGroupEarlier: (column) => `Move ${column} earlier`,
    moveGroupLater: (column) => `Move ${column} later`,
    removeGroup: (column) => `Remove ${column} grouping`,

    groupByColumn: 'Group by this column',
    ungroupColumn: 'Ungroup this column',

    groupFooter: (key) => `Total: ${key}`,
    grandTotal: (count) => `Total (${count})`,
    groupLoaded: (key, count) => `${key} (${count} loaded)`,
    groupFooterLoaded: (key, count) => `Total - ${key} (${count} loaded)`,
    grandTotalLoaded: (count) => `Total (${count} loaded)`,

    rangeCells: (count) => `${count} cells`,
    rangeShape: (rows, columns) => `${rows}x${columns}`,
    rangeSum: 'Sum',
    rangeAvg: 'Avg',
    rangeMin: 'Min',
    rangeMax: 'Max',

    commandPaletteTitle: 'Command palette',
    commandPalettePlaceholder: 'Type a command...',
    commandPaletteEmpty: 'No matching commands',
    commandGroupDefault: 'Commands',

    commandShowColumn: (column) => `Show column: ${column}`,
    commandHideColumn: (column) => `Hide column: ${column}`,
    commandUnpinColumn: (column) => `Unpin column: ${column}`,
    commandPinColumnLeft: (column) => `Pin left: ${column}`,
    commandPinColumnRight: (column) => `Pin right: ${column}`,
    commandGroupByColumn: (column) => `Group by: ${column}`,
    commandUngroupColumn: (column) => `Ungroup: ${column}`,
    commandExpandAllGroups: 'Expand all groups',
    commandCollapseAllGroups: 'Collapse all groups',
    commandClearGrouping: 'Clear grouping',
    commandCopyRange: 'Copy selected range',
    commandFillDown: 'Fill down',
    commandFillRight: 'Fill right',
    commandGroupColumns: 'Columns',
    commandGroupGrouping: 'Grouping',
    commandGroupClipboard: 'Clipboard',

    findTitle: 'Find & replace',
    findPlaceholder: 'Find in grid...',
    replacePlaceholder: 'Replace with...',
    findCaseSensitive: 'Match case',
    findWholeCell: 'Match whole cell',
    findPrevious: 'Previous match',
    findNext: 'Next match',
    findClose: 'Close find',
    findReplaceOne: 'Replace',
    findReplaceAll: 'Replace all',
    commandFind: 'Find & replace',
    findCount: (current, total) => `${current} / ${total}`,
    findNoMatch: 'No matches',
    findNoWritable: (total) => `${total} found, none editable`,
    findReplaced: (cells) => `Replaced ${cells}`,
    findCountLoaded: (current, total) => `${current} / ${total} loaded`,
    findNoMatchLoaded: 'No matches in loaded rows',
    findServerReadOnly: 'Replace is off for server-loaded rows',

    viewsLabel: 'Views',
    viewsEmpty: 'No saved views',
    viewsPick: 'Pick a view',
    viewNamePlaceholder: 'Name this view...',
    viewSave: 'Save',
    viewUpdate: 'Update',
    viewRevert: 'Revert',
    viewRemove: 'Delete',
    viewShare: 'Copy link',
    viewShareCopied: 'Link copied',
    viewModified: 'edited',
    commandSaveView: 'Save current view',
    viewShareTooLong: (length) => `Too big to link (${length} chars): save it as a view`,

    formatLabel: 'Formatting',
    formatEmpty: 'No formatting rules',
    formatAdd: 'Add rule',
    formatClear: 'Clear',
    formatColumn: 'Column',
    formatKind: 'Rule',
    formatKindColorScale: 'Colour scale',
    formatKindDataBar: 'Data bar',
    formatKindDuplicates: 'Duplicates',
    formatKindTopN: 'Top values',
    formatKindExpression: 'Expression',
    formatTopCount: 'How many',
    formatExpressionPlaceholder: 'status = "overdue"',
    formatWholeRow: 'Whole row',
    formatRuleName: (kind, column) => `${kind}: ${column}`,
    formatRemoveRule: (rule) => `Remove ${rule}`,
    formatBadExpression: (message) => `Will not parse: ${message}`,

    toolPanelTitle: 'Tools',
    toolPanelColumns: 'Columns',
    toolPanelGroup: 'Groups',
    toolPanelValues: 'Values',
    toolPanelSearch: 'Search columns...',
    toolPanelShowAll: 'Show all',
    toolPanelHideAll: 'Hide all',
    toolPanelEmpty: 'No column matches',
    toolPanelMoveUp: (column) => `Move ${column} earlier`,
    toolPanelMoveDown: (column) => `Move ${column} later`,
    toolPanelNoAggregation: 'None',
    toolPanelActions: (column) => `Column actions: ${column}`,
    toolPanelCollapse: 'Collapse panel',
    toolPanelExpand: 'Expand panel',

    filterTitle: 'Filter',
    filterEmpty: 'No conditions yet',
    filterAddCondition: 'Add condition',
    filterAddGroup: 'Add group',
    filterRemove: 'Remove',
    filterJoin: (join) => (join === 'and' ? 'AND' : 'OR'),
    filterNot: 'NOT',
    filterBuilderColumn: 'Column',
    filterBuilderOperator: 'Operator',
    filterBuilderValue: 'Value',
    filterValueTo: 'To',
    filterTrue: 'True',
    filterFalse: 'False',
    filterOp: (op) =>
        (
            ({
                contains: 'contains',
                notContains: 'does not contain',
                equals: 'equals',
                notEqual: 'does not equal',
                startsWith: 'starts with',
                endsWith: 'ends with',
                gt: 'greater than',
                gte: 'greater or equal',
                lt: 'less than',
                lte: 'less or equal',
                between: 'between',
                before: 'before',
                after: 'after',
                in: 'one of',
                blank: 'is blank',
                notBlank: 'is not blank'
            }) as Record<string, string>
        )[op] ?? op,
    filterServerHandled: 'Answered by your backend',

    importTitle: 'Import',
    importDropHere: 'Drop a spreadsheet here',
    importChooseFile: 'Choose a file',
    importPaste: 'Paste from clipboard',
    importEmpty: 'That file holds no rows',
    importUnknownFormat: (name) => `${name} is not a shape this reads`,
    importHeaderRow: 'First row names columns',
    importSheet: 'Sheet',
    importColumnFrom: 'Source column',
    importSkipColumn: 'Do not import',
    importMatchTitle: 'Match columns',
    importReviewTitle: 'Check before adding',
    importBack: 'Back',
    importNext: 'Check',
    importCancel: 'Cancel',
    importAddRows: (count) => `Add all (${count})`,
    importAddValid: (count) => `Add ready (${count})`,
    importIssues: (count) => `To check: ${count}`,
    importReady: 'Every row is ready',
    importNotNumber: (header) => `${header} is not a number`,
    importNotDate: (header) => `${header} is not a date`,
    importNotBoolean: (header) => `${header} is not a yes or a no`,
    importInvalid: (header) => `${header} was refused`,
    importDuplicate: (key) => `${key} is in this file more than once`,
    importExisting: (key) => `${key} is already in this grid`,
    importServerRefusal: 'A server owns these rows, so an import cannot stage them here',
    importRowCount: (count) => `${count} rows to read`,
    importTooBig: (name, megabytes) => `${name} is over a limit of ${megabytes} MB`,
    importMatched: (matched, total) => `${matched} of ${total} columns matched`,
    importNothingMatched:
        'Nothing matched. Pick a source column for each one you want, or check that first row is a header'
}

/** Overrides over a base language; operator maps merge one entry at a time. */
export function mergeLabels(
    overrides: DataGridLabelsInput | undefined,
    base: DataGridLabels = defaultLabels
): DataGridLabels {
    if (!overrides) return base
    return {
        ...base,
        ...overrides,
        textOps: { ...base.textOps, ...overrides.textOps },
        numberOps: { ...base.numberOps, ...overrides.numberOps },
        dateOps: { ...base.dateOps, ...overrides.dateOps }
    }
}
