/**
 * Bundles the exact lucide icons the grid renders into a local Iconify
 * collection, so `@iconify/svelte` resolves them from memory instead of
 * fetching them from the Iconify API at runtime.
 *
 * The set is every `lucide:*` name the grid's own source passes to an icon,
 * plus any sv5ui default sv5ui does not bundle for itself — normally none.
 *
 * The icons sv5ui components reach for on their own (the pagination chevrons,
 * the rating star, the external-link arrow) are already registered by sv5ui's
 * `Icon.svelte` module script, which runs before the grid renders. Restating
 * them here bought nothing; the version that did also shipped `loader-2`,
 * which sv5ui never asks for.
 *
 * Run with `npm run generate:icons`. The output is committed, so a normal
 * install and build never need `@iconify-json/lucide`.
 */
import { createRequire } from 'node:module'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const require = createRequire(import.meta.url)
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const LIB = path.join(ROOT, 'src/lib')
const OUT = path.join(LIB, 'components/internal/icons.data.ts')

/**
 * Icons sv5ui components fall back to that sv5ui does not already ship.
 *
 * `Icon.svelte` registers sv5ui's own bundle from its module script, so every
 * default it covers is resolved before the grid renders anything — the
 * pagination chevrons, the rating star, the external-link arrow. Restating
 * them here would only duplicate bytes.
 *
 * The gap this closes is drift: if sv5ui ever names a default it stops
 * bundling, that icon would start fetching with nothing to notice. Normally
 * this returns nothing.
 *
 * It replaces a hand-written list of five names, which had guessed `loader-2`
 * where sv5ui uses `loader-circle` — shipping an icon nothing renders.
 */
async function sv5uiUnbundledDefaults() {
    // Resolved, not imported: `sv5ui/config` is not an export subpath, and the
    // root entry pulls `.svelte` files node cannot load. Both files sit beside
    // that entry and are plain JS.
    const dist = path.dirname(fileURLToPath(import.meta.resolve('sv5ui')))
    const { iconsDefaults } = await import(pathToFileURL(path.join(dist, 'config.js')).href)
    const { bundledIcons } = await import(
        pathToFileURL(path.join(dist, 'components/Icon/bundled.js')).href
    )

    const shipped = new Set()
    for (const collection of bundledIcons) {
        for (const name of Object.keys(collection.icons ?? {})) {
            shipped.add(`${collection.prefix}:${name}`)
        }
    }

    const names = new Set()
    for (const value of Object.values(iconsDefaults)) {
        if (shipped.has(String(value))) continue
        const [prefix, name] = String(value).split(':')
        if (prefix !== 'lucide') {
            console.error(
                `sv5ui default ${value} is neither bundled by sv5ui nor in the lucide ` +
                    'collection. Bundle it from its own @iconify-json package.'
            )
            process.exit(1)
        }
        names.add(name)
    }
    return names
}

function walk(dir, out = []) {
    for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry)
        if (statSync(full).isDirectory()) walk(full, out)
        else if (/\.(svelte|ts)$/.test(entry) && !/\.(test|spec)\./.test(entry)) out.push(full)
    }
    return out
}

function scanUsedIcons() {
    const names = new Set()
    for (const file of walk(LIB)) {
        const text = readFileSync(file, 'utf8')
        for (const match of text.matchAll(/lucide:([a-z0-9-]+)/g)) names.add(match[1])
    }
    return names
}

/** Follows alias chains so a used name always lands on a concrete icon body. */
function resolveBody(collection, name, seen = new Set()) {
    if (collection.icons[name]) return collection.icons[name].body
    const alias = collection.aliases?.[name]
    if (!alias || seen.has(name)) return null
    seen.add(name)
    return resolveBody(collection, alias.parent, seen)
}

const lucide = require('@iconify-json/lucide/icons.json')

const used = scanUsedIcons()
for (const name of await sv5uiUnbundledDefaults()) used.add(name)

const icons = {}
const missing = []
for (const name of [...used].sort()) {
    const body = resolveBody(lucide, name)
    if (body === null) missing.push(name)
    else icons[name] = { body }
}

if (missing.length > 0) {
    console.error(`Unknown lucide icons (typo, or removed upstream): ${missing.join(', ')}`)
    process.exit(1)
}

const collection = { prefix: 'lucide', width: lucide.width, height: lucide.height, icons }

const banner =
    '// Generated by scripts/generate-icons.mjs — do not edit by hand.\n' +
    '// Run `npm run generate:icons` after changing the icons the grid uses.\n'

const file =
    banner +
    "import type { IconifyJSON } from '@iconify/svelte'\n\n" +
    `export const datagridIcons: IconifyJSON = ${JSON.stringify(collection, null, 4)}\n`

writeFileSync(OUT, file)
console.log(`Wrote ${Object.keys(icons).length} icons to ${path.relative(ROOT, OUT)}`)
