/**
 * Bundles the exact lucide icons the grid renders into a local Iconify
 * collection, so `@iconify/svelte` resolves them from memory instead of
 * fetching them from the Iconify API at runtime.
 *
 * The set is the union of two sources:
 *   1. Every `lucide:*` name the grid's own source passes to an icon.
 *   2. The default icons the sv5ui parts the grid renders pull themselves —
 *      the Select's chevron, the Pagination arrows, and so on. These are not
 *      in the grid's source, but they appear in its UI, so leaving them out
 *      would mean the footer and menus still hit the network.
 *
 * Run with `npm run generate:icons`. The output is committed, so a normal
 * install and build never need `@iconify-json/lucide`.
 */
import { createRequire } from 'node:module'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const require = createRequire(import.meta.url)
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const LIB = path.join(ROOT, 'src/lib')
const OUT = path.join(LIB, 'components/internal/icons.data.ts')

/**
 * Icons the sv5ui components the grid renders pull from their own defaults,
 * resolved from sv5ui's `iconsDefaults`. Kept explicit so a reader can see why
 * each one ships even though the grid never names it.
 */
const SV5UI_CHROME_ICONS = [
    'chevron-left', // Pagination prev
    'chevron-right', // Pagination next, submenu markers
    'chevrons-left', // Pagination first
    'chevrons-right', // Pagination last
    'loader-2' // Select / Input busy state
]

function walk(dir, out = []) {
    for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry)
        if (statSync(full).isDirectory()) walk(full, out)
        else if (/\.(svelte|ts)$/.test(entry) && !/\.(test|spec)\./.test(entry)) out.push(full)
    }
    return out
}

function scanUsedIcons() {
    const names = new Set()
    for (const file of walk(LIB)) {
        const text = readFileSync(file, 'utf8')
        for (const match of text.matchAll(/lucide:([a-z0-9-]+)/g)) names.add(match[1])
    }
    return names
}

/** Follows alias chains so a used name always lands on a concrete icon body. */
function resolveBody(collection, name, seen = new Set()) {
    if (collection.icons[name]) return collection.icons[name].body
    const alias = collection.aliases?.[name]
    if (!alias || seen.has(name)) return null
    seen.add(name)
    return resolveBody(collection, alias.parent, seen)
}

const lucide = require('@iconify-json/lucide/icons.json')

const used = scanUsedIcons()
for (const name of SV5UI_CHROME_ICONS) used.add(name)

const icons = {}
const missing = []
for (const name of [...used].sort()) {
    const body = resolveBody(lucide, name)
    if (body === null) missing.push(name)
    else icons[name] = { body }
}

if (missing.length > 0) {
    console.error(`Unknown lucide icons (typo, or removed upstream): ${missing.join(', ')}`)
    process.exit(1)
}

const collection = { prefix: 'lucide', width: lucide.width, height: lucide.height, icons }

const banner =
    '// Generated by scripts/generate-icons.mjs — do not edit by hand.\n' +
    '// Run `npm run generate:icons` after changing the icons the grid uses.\n'

const file =
    banner +
    "import type { IconifyJSON } from '@iconify/svelte'\n\n" +
    `export const datagridIcons: IconifyJSON = ${JSON.stringify(collection, null, 4)}\n`

writeFileSync(OUT, file)
console.log(`Wrote ${Object.keys(icons).length} icons to ${path.relative(ROOT, OUT)}`)
